AllCops:
  Exclude:
    - Guardfile
    - bin/*
    - db/schema.rb
    - db/migrate/*
    - test/test_helper.rb
    - vendor/**/*

Metrics/LineLength:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/AccessModifierIndentation:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Style/TrailingCommaInLiteral:
  Enabled: false

Metrics/CyclomaticComplexity:
  Exclude:
    - app/models/spitcast.rb

Lint/UnusedMethodArgument:
  Exclude:
    - app/models/forecast.rb
