AllCops:
  Exclude:
    - Guardfile
    - bin/*
    - db/schema.rb
    - db/migrate/*
    - node_modules/**/*
    - test/test_helper.rb
    - vendor/**/*

Layout/AccessModifierIndentation:
  Enabled: false

Lint/UnusedMethodArgument:
  Exclude:
    - app/models/forecast.rb

Lint/Void:
  Exclude:
    - lib/tasks/surfline.rake

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/LineLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Rails/InverseOf:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FormatStringToken:
  Enabled: false

Style/TrailingCommaInLiteral:
  Enabled: false
